language: node_js
node_js:
- '10'
before_install:
- npm install -D
script:
- npm run build
deploy:
  provider: releases
  api_key:
    secure: UihIKD0/wWewluTmQRKTO4QKtLWu40I7sXnyeQ1x6FcNWAXkl+3/FYniqSHqd2xAB7bjOGr7SYBkAAe1DW7e5lRRp9Nj0V4Nfk7hK6K1u5poDAzr52VkDByWm6+fYB7CvEWPp9JM/V4zKXC64jVy2hiV2EFHgf1KsCpEOgjiWNDBdjok5bkXqW91PKgf8F0B1BXsOzfyhfcMQlKkozGW2jnHHiR6oL6t7+TJ/XcpMbq1/FKXc/OHJt15yQk1hM493ZaN0x3w4ITTLfl96utpxVBhqbiJSEn2+zIheJrzdv3HWUqo5m3B+FMjKZXyLkBU/J7nGyrQskTa5Xb/poc1+iDClaMqWAfHCwnO9Dw+qTBMXY+sl3QFqL/bzsU8/6Hxa6fpRDhVyubiG+vH8FCyvHVBhHrPmHYTQeT4p7gxXMhBuOFCq8p4G7Qd71T2IaG7Iwsr00QjL+mQgBNdfxBePwQFM9LWTi89vKyex3btXulFL5P8qH5Ys85tVOoqRiZO5dyn9Qe05ttl7zFz0ixwES67uO4MZbfZHzwUGKd/f7k8PrUkU/0/7rnsLIBaYAFI2rAX/E6H0rJ31bsQyt8IDUc+TSaZ+qfmcx/wdIHffe+j7G+W58j+LYdQgbeBobKpWHaL69x6aoYjft2jVl9TS7StACExaUfJ5jb3R7taWV0=
  file: 
    - bin/cfl-converter-linux
    - bin/cfl-converter-macos
    - bin/cfl-converter-win.exe
  on:
    repo: dhkatz/cfl-converter
